# Generated by Django 2.2.dev20180806210306 on 2018-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cachesuap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['nome'], 'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='papel',
            options={'ordering': ['nome'], 'verbose_name': 'Papel', 'verbose_name_plural': 'Papeis'},
        ),
        migrations.AddField(
            model_name='curso',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='codigo_moodle',
            field=models.IntegerField(unique=True, verbose_name='Código Moodle'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='codigo_suap',
            field=models.IntegerField(unique=True, verbose_name='Código SUAP'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_moodle',
            field=models.IntegerField(help_text='Deve ser o mesmo código do Moodle', unique=True, verbose_name='Código Moodle'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_suap',
            field=models.IntegerField(unique=True, verbose_name='Código SUAP'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='codigo_moodle',
            field=models.IntegerField(unique=True, verbose_name='Código Moodle'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='codigo_suap',
            field=models.IntegerField(unique=True, verbose_name='Código SUAP'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
