# Generated by Django 2.2.dev20180806210306 on 2018-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180828_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='papel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
    ]
